#!/usr/bin/env bash

# Try to run at the root of your HPCarver install.
dir=$(basename "$(pwd)")
while [[ "$dir" != "HPCarver" ]] && [[ "$dir" != "/" ]]
do
    cd ..
    dir=$(basename "$(pwd)")
done

if [[ "$dir" != "HPCarver" ]]; then
    echo "Please run script from HPCarver directory!"
    exit 1
fi

cd out/tests || exit

if [[ -f test_serialcarve ]]; then
    ./test_serialcarve
fi

if [[ -f test_ompcarve ]]; then
    ./test_ompcarve
fi

# For now, assumes that all cuda tests are run on the cluster.
if [[ -f test_cudacarve ]]; then
    srun --gres=gpu ./test_cudacarve
fi

if [[ -f test_rajacarve ]]; then
    ./test_rajacarve
fi
