#!/usr/bin/env bash

# INSTALL SCRIPT OPTIONAL -- you are welcome to configure this yourself!

# Try to place the install at the root of your RAJA.
dir=$(basename `pwd`)
if [[ "$dir" == "scripts" ]]; then
    cd ..
fi

dir=$(basename `pwd`)
if [[ "$dir" != "HPCarver" ]]; then
    echo "Please run script from HPCarver root or scripts directory!"
    exit 1
fi

# if any required directories are missing, force a clean install
if [[ ! -d RAJA-install ]] || [[ ! -d RAJA ]] || [[ ! -d RAJA-build ]]; then
    rm -r RAJA-install
    rm -r RAJA
    rm -r RAJA-build

    git clone --recursive https://github.com/LLNL/RAJA.git
    mkdir RAJA-install
    mkdir RAJA-build

    # build RAJA 
    cd RAJA-build
    cmake -DRAJA_ENABLE_TESTS=Off -DRAJA_ENABLE_EXAMPLES=Off -DRAJA_ENABLE_EXERCISES=Off -DCMAKE_INSTALL_PREFIX=../RAJA-install -DENABLE_CUDA=On -DENABLE_OPENMP=On ../RAJA
    make -j && make install
fi
