#!/usr/bin/env bash

# INSTALL SCRIPT OPTIONAL -- you are welcome to configure this yourself!

# Try to place the install at the root of your RAJA.
dir=$(basename `pwd`)
while [[ "$dir" != "HPCarver" ]] && [[ "$dir" != "/" ]]
do
    cd ..
    dir=$(basename `pwd`)
done

if [[ "$dir" != "HPCarver" ]]; then
    echo "Please run script from HPCarver directory!"
    exit 1
fi

# Parse install options
build_options="-DRAJA_ENABLE_TESTS=Off -DRAJA_ENABLE_EXAMPLES=Off -DRAJA_ENABLE_EXERCISES=Off -DCMAKE_INSTALL_PREFIX=../RAJA-install -DENABLE_OPENMP=On"
if [[ $1 == "true" ]]; then
    echo "saw option true; building with CUDA support"
    build_options="$build_options -DENABLE_CUDA=On"
else
    echo "did not see option true; building without CUDA support"
fi


# if any required directories are missing, force a clean install
if [[ ! -d RAJA-install ]] || [[ ! -d RAJA ]] || [[ ! -d RAJA-build ]]; then
    rm -r RAJA-install
    rm -r RAJA
    rm -r RAJA-build

    git clone --recursive https://github.com/LLNL/RAJA.git
    mkdir RAJA-install
    mkdir RAJA-build

    # build RAJA 
    cd RAJA-build
    cmake $build_options ../RAJA
    make -j && make install
fi
