#!/usr/bin/env bash

# Perform timing tests
# author: Will Morris

# proceeding sequentially for ease of interpretation
cd ../out

image=duke_dog.ppm
# Reducing images to progressively lower sizes
sizes=(600 500 400)
# Running three trials
trials=(1 2 3)

# If using a job manager (slurm is currently the only one supported)
# Here is where the prefix will be stored
standard_prefix=""
cuda_prefix=""

if [[ $1 == "slurm" ]]; then
    echo "Found slurm argument; running with support for slurm"
    standard_prefix="srun"
    cuda_prefix="--gres=gpu"
else
    echo "no slurm argument found; running without slurm support"
fi

if [[ -f hpc_serial ]]; then
    for size in "${sizes[@]}"; do
        for trial in "${trials[@]}"; do
            echo "hpc_serial, size $size, trial $trial"
            $standard_prefix ./hpc_serial $image out.ppm $size $size
        done
    done
fi

if [[ -f hpc_omp ]]; then
    for size in "${sizes[@]}"; do
        for trial in "${trials[@]}"; do
            echo "hpc_omp, size $size, trial $trial"
            $standard_prefix ./hpc_omp $image out_omp.ppm $size $size
        done
    done
fi

if [[ -f hpc_raja ]]; then
    for size in "${sizes[@]}"; do
        for trial in "${trials[@]}"; do
            echo "hpc_raja, size $size, trial $trial"
            $standard_prefix ./hpc_raja $image out_raja.ppm $size $size
        done
    done
fi

if [[ -f hpc_cuda ]]; then
    for size in "${sizes[@]}"; do
        for trial in "${trials[@]}"; do
            echo "hpc_cuda, size $size, trial $trial"
            $standard_prefix $cuda_prefix ./hpc_cuda $image out_cu.ppm $size $size
        done
    done
fi
