#!/usr/bin/env bash

# Perform timing tests
# author: Will Morris

# proceeding sequentially for ease of interpretation
cd ../out

image=duke_dog.ppm
# Reducing images to progressively lower sizes
sizes=(600 500 400)
# Running three trials
trials=(1 2 3)

if [[ -f hpc_serial ]]; then
    for size in "${sizes[@]}"; do
        for trial in "${trials[@]}"; do
            echo "hpc_serial, size $size, trial $trial"
            ./hpc_serial $image out.ppm $size $size
        done
    done
fi

if [[ -f hpc_omp ]]; then
    for size in "${sizes[@]}"; do
        for trial in "${trials[@]}"; do
            echo "hpc_omp, size $size, trial $trial"
            ./hpc_omp $image out_omp.ppm $size $size
        done
    done
fi

if [[ -f hpc_raja ]]; then
    for size in "${sizes[@]}"; do
        for trial in "${trials[@]}"; do
            echo "hpc_raja, size $size, trial $trial"
            ./hpc_raja $image out_raja.ppm $size $size
        done
    done
fi

# Not running CUDA tests outside of the cluster.
